---
title: "Analyzing Trends in Office Attendance \nIn Major US Markets"
author: "Team ACHE: \nAnh, Caden, and Heidi!"
format: revealjs
editor: visual
---

## The Issue

- Predicting who will show up to offices can be hard after covid

- What if you care about attendance at an office you choose? What if the market you choose to settle in affects who attends work?

- Using data from Kastle, we talk about the occupancy rate

## Occupancy Rate

(show plot of seasonal trend with occupancy)

comment on that it is seasonal time series data, remove seasonal trend

## Occupancy Rate: Deseasonalized

(show plot of occupancy without season changes)

Talk about how we want to show factors that will change this over time

## Factors That May Affect Office Attendance

1. Extreme Weather Events
2. Unemployment Rate
3. Traffic Congestion
4. Covid Cases
5. State Political Affiliation
6. Work-from-home Rate

## Example Factor: Work-from-home Rate

- data from Kastle

- guide through example of people working in person again increasing (?)

- this suggests that since people returning from covid/2020 are now less likely to work in person, therefore


## Our Research Question 

<br>

<br>

<div style="text-align: center; font-size: 1.5em; font-weight: bold;">
What variables explain the increasing trend of post-COVID office occupancy across major markets?
</div>

## Analysis



## Other


extra yap: 
What trends explain the trend what is making people return to office, and is it dependent on city



## Credit

* Help making the [Quarto Presentation](https://quarto.org/docs/presentations/)

* Data Sources
  * [Covid Cases Data](https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/)
  * [Extreme Weather Event](https://www.ncdc.noaa.gov/stormevents/)
  * [Traffic Congestion](https://grok.com/share/bGVnYWN5_4367bb2c-71a2-4443-92f3-cf90b150b7cf)
  * For Occupancy Rate and Unemployment Rate data, please see resources given to us

## Thanks! {.center}
